networks:                                                                                                                                                     
  web:                                                                                                                                                        
    external: true                                                                                                                                            
  lan:                                                                                                                                                        
    external: false                                                                                                                                           
    name: lan_${NAME}

services:

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SITE_URL: '${SITE_URL}'
      ADMIN_USER: '${ADMIN_USER}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      ADMIN_EMAIL: '${ADMIN_EMAIL}'
      WP_TITLE: '${WP_TITLE}'
      WP_IS_MULTISITE_SUBDOMAIN: '${WP_IS_MULTISITE_SUBDOMAIN}'        
      NAME: '${NAME}'
      WORDPRESS_DB_HOST: 'mysql'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_DB_NAME: 'wordpress'     
    volumes:
      - ./ecv_data/wordpress:/var/www/html
    networks:
        - web
        - lan
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NAME}.entryPoints=websecure
      - traefik.http.routers.${NAME}.rule=Host(`${NAME}.jrcan.dev`)
      - traefik.http.routers.${NAME}.tls=true
      - traefik.http.routers.${NAME}.tls.certresolver=myresolver

  db:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER:  '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}' 
    volumes:
      - db:/var/lib/mysql
    networks:
        - lan


volumes:
  wordpress:
  db: