version: "3.3"

services:
  wordpress:

    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SITE_URL: '${SITE_URL}'
      ADMIN_USER: '${ADMIN_USER}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      ADMIN_EMAIL: '${ADMIN_EMAIL}'
      WP_TITLE: '${WP_TITLE}'
      WP_IS_MULTISITE_SUBDOMAIN: '${WP_IS_MULTISITE_SUBDOMAIN}'        
      NAME: '${NAME}'
      WORDPRESS_DB_HOST: 'mysql'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_DB_NAME: 'wordpress'
    volumes:
      - wordpress:/var/www/html
    ports:
      - "8080:80"
    networks:
      - lan

  db:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER:  '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lan

networks:
  lan:                                                                                                                                                        
    external: false                                                                                                                                           
    name: lan_${NAME}

volumes:
  mysql_data:
  wordpress: